server:
  port: 8080

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://103.36.173.35:32323/device_prod?allowMultiQueries=true&amp;useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;useSSL=true
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity
